package com.gira.backend.service;

import com.gira.backend.dto.TicketActivityDTO;
import com.gira.backend.dto.TicketDTO;
import com.gira.backend.dto.TicketRequest;
import com.gira.backend.model.Ticket;
import com.gira.backend.model.TicketActivity;
import com.gira.backend.model.User;
import com.gira.backend.repository.TicketActivityRepository;
import com.gira.backend.repository.TicketRepository;
import com.gira.backend.repository.UserRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class TicketService {

    private final TicketRepository ticketRepository;
    private final UserRepository userRepository;
    private final UserService userService;
    private final EmailService emailService;
    private final TicketActivityRepository activityRepository;

    public TicketService(TicketRepository ticketRepository,
            UserRepository userRepository,
            UserService userService,
            EmailService emailService,
            TicketActivityRepository activityRepository) {
        this.ticketRepository = ticketRepository;
        this.userRepository = userRepository;
        this.userService = userService;
        this.emailService = emailService;
        this.activityRepository = activityRepository;
    }

    // ── CRUD ──────────────────────────────────────────────────────

    /** Create a new ticket (raised by a worker). */
    public Optional<TicketDTO> createTicket(TicketRequest request) {
        User worker = userRepository.findById(request.getWorkerId()).orElse(null);
        if (worker == null)
            return Optional.empty();

        Ticket ticket = new Ticket();
        ticket.setTitle(request.getTitle());
        ticket.setDescription(request.getDescription());
        ticket.setPriority(parsePriority(request.getPriority()));
        ticket.setWorker(worker);

        if (request.getProviderId() != null) {
            userRepository.findById(request.getProviderId()).ifPresent(ticket::setProvider);
        }

        Ticket saved = ticketRepository.save(ticket);
        logActivity(saved, worker, "CREATED", "Ticket generated by worker.");
        return Optional.of(toDTO(saved));
    }

    /** Get all tickets (manager view). */
    public List<TicketDTO> getAllTickets() {
        return ticketRepository.findAll().stream()
                .map(this::toDTO)
                .collect(Collectors.toList());
    }

    /** Get tickets raised by a specific worker. */
    public List<TicketDTO> getTicketsByWorker(Long workerId) {
        return userRepository.findById(workerId)
                .map(worker -> ticketRepository.findByWorker(worker).stream()
                        .map(this::toDTO)
                        .collect(Collectors.toList()))
                .orElse(List.of());
    }

    /** Get tickets assigned to a specific provider. */
    public List<TicketDTO> getTicketsByProvider(Long providerId) {
        return userRepository.findById(providerId)
                .map(provider -> ticketRepository.findByProvider(provider).stream()
                        .map(this::toDTO)
                        .collect(Collectors.toList()))
                .orElse(List.of());
    }

    /** Get a single ticket by ID. */
    public Optional<TicketDTO> getTicketById(Long id) {
        return ticketRepository.findById(id).map(this::toDTO);
    }

    /**
     * Assign a provider to a ticket and move it to IN_PROGRESS. (Backward
     * compatibility)
     */
    public Optional<TicketDTO> assignProvider(Long ticketId, Long providerId) {
        return assignProvider(ticketId, providerId, "GIRA Manager");
    }

    /**
     * Assign a provider to a ticket, move to IN_PROGRESS, and send email
     * notification.
     */
    public Optional<TicketDTO> assignProvider(Long ticketId, Long providerId, String managerName) {
        return ticketRepository.findById(ticketId)
                .flatMap(ticket -> userRepository.findById(providerId).map(provider -> {
                    // Update ticket
                    ticket.setProvider(provider);
                    ticket.setStatus(Ticket.Status.IN_PROGRESS);
                    Ticket savedTicket = ticketRepository.save(ticket);
                    TicketDTO dto = toDTO(savedTicket);

                    // Send Email Notification
                    try {
                        emailService.sendTicketAssignmentNotification(
                                provider.getEmail(),
                                dto.getTicketNumber(),
                                ticket.getTitle(),
                                ticket.getDescription(),
                                ticket.getPriority().name(),
                                null, // Deadline not in model yet, fallback to "Check dashboard"
                                managerName);
                    } catch (Exception e) {
                        // Log but don't fail the assignment if email fails
                        org.slf4j.LoggerFactory.getLogger(TicketService.class)
                                .error("Failed to send assignment notification for ticket {}: {}", ticketId,
                                        e.getMessage());
                    }

                    User manager = userRepository.findAll().stream()
                            .filter(u -> u.getRole() == User.Role.MANAGER).findFirst().orElse(null);
                    logActivity(savedTicket, manager, "ASSIGNED",
                            "Assigned to " + provider.getName() + " by " + managerName);

                    return dto;
                }));
    }

    /** Update the status of a ticket. */
    public Optional<TicketDTO> updateStatus(Long ticketId, String statusStr) {
        return ticketRepository.findById(ticketId).map(ticket -> {
            Ticket.Status oldStatus = ticket.getStatus();
            try {
                Ticket.Status newStatus = Ticket.Status.valueOf(
                        statusStr.toUpperCase().replace("-", "_"));
                ticket.setStatus(newStatus);
            } catch (IllegalArgumentException ignored) {
            }
            Ticket saved = ticketRepository.save(ticket);
            User actingUser = ticket.getProvider() != null ? ticket.getProvider()
                    : userRepository.findAll().stream().filter(u -> u.getRole() == User.Role.MANAGER).findFirst()
                            .orElse(null);
            logActivity(saved, actingUser, "STATUS_UPDATE",
                    "Status changed from " + oldStatus + " to " + ticket.getStatus());
            return toDTO(saved);
        });
    }

    /** Set the expected resolution date for a ticket. */
    public Optional<TicketDTO> setResolutionDate(Long ticketId, LocalDateTime date) {
        return ticketRepository.findById(ticketId).map(ticket -> {
            ticket.setExpectedResolutionDate(date);
            Ticket saved = ticketRepository.save(ticket);
            User actingUser = ticket.getProvider() != null ? ticket.getProvider()
                    : userRepository.findAll().stream().filter(u -> u.getRole() == User.Role.MANAGER).findFirst()
                            .orElse(null);
            logActivity(saved, actingUser, "METADATA_UPDATE", "Expected resolution date set to " + date);
            return toDTO(saved);
        });
    }

    /** Send a custom email (Gmail theme) related to a ticket. */
    public boolean sendCustomTicketEmail(Long ticketId, String toType, String subject, String body) {
        return ticketRepository.findById(ticketId).map(ticket -> {
            String targetEmail = null;
            if ("worker".equalsIgnoreCase(toType)) {
                if (ticket.getWorker() != null)
                    targetEmail = ticket.getWorker().getEmail();
            } else if ("manager".equalsIgnoreCase(toType)) {
                // Assuming manager email is wanted, currently we don't have a direct 'manager'
                // field
                // but usually the first admin/manager in system or a specific hardcoded one.
                // For now, let's look for a user with role 'MANAGER' or use a fallback.
                targetEmail = userRepository.findAll().stream()
                        .filter(u -> u.getRole() == User.Role.MANAGER)
                        .map(User::getEmail)
                        .findFirst().orElse("manager@gira.com");
            } else if ("provider".equalsIgnoreCase(toType)) {
                if (ticket.getProvider() != null)
                    targetEmail = ticket.getProvider().getEmail();
            } else {
                // assume it's a direct email if not a keyword
                targetEmail = toType;
            }

            if (targetEmail != null) {
                emailService.sendCustomEmail(targetEmail, subject, body);
                return true;
            }
            return false;
        }).orElse(false);
    }

    /** Send completion summary email to worker. */
    public void sendCompletionSummary(Long ticketId, String summary) {
        ticketRepository.findById(ticketId).ifPresent(ticket -> {
            logActivity(ticket, ticket.getProvider(), "RESOLUTION_SUMMARY", summary);
            if (ticket.getWorker() != null && ticket.getWorker().getEmail() != null) {
                TicketDTO dto = toDTO(ticket);
                emailService.sendCompletionSummaryEmail(
                        ticket.getWorker().getEmail(),
                        dto.getTicketNumber(),
                        ticket.getTitle(),
                        summary);
            }
        });
    }

    /** Delete a ticket. */
    public boolean deleteTicket(Long ticketId) {
        if (!ticketRepository.existsById(ticketId))
            return false;
        ticketRepository.deleteById(ticketId);
        return true;
    }

    // ── Helpers ───────────────────────────────────────────────────

    private Ticket.Priority parsePriority(String p) {
        if (p == null)
            return Ticket.Priority.MEDIUM;
        try {
            return Ticket.Priority.valueOf(p.toUpperCase());
        } catch (IllegalArgumentException e) {
            return Ticket.Priority.MEDIUM;
        }
    }

    private String formatStatus(Ticket.Status status) {
        return switch (status) {
            case IN_PROGRESS -> "in-progress";
            default -> status.name().toLowerCase();
        };
    }

    public TicketDTO toDTO(Ticket ticket) {
        TicketDTO dto = new TicketDTO();
        dto.setId(ticket.getId());
        dto.setTicketNumber(String.format("TKT-%04d", ticket.getId()));
        dto.setTitle(ticket.getTitle());
        dto.setDescription(ticket.getDescription());
        dto.setStatus(formatStatus(ticket.getStatus()));
        dto.setPriority(ticket.getPriority().name().toLowerCase());
        dto.setWorker(userService.toDTO(ticket.getWorker()));
        dto.setProvider(userService.toDTO(ticket.getProvider()));
        dto.setCreatedAt(ticket.getCreatedAt());
        dto.setUpdatedAt(ticket.getUpdatedAt());
        dto.setExpectedResolutionDate(ticket.getExpectedResolutionDate());
        return dto;
    }

    public Optional<TicketDTO> forwardTicket(Long ticketId, Long providerId, String reason) {
        return ticketRepository.findById(ticketId).map(ticket -> {
            User provider = userRepository.findById(providerId).orElse(null);
            ticket.setStatus(Ticket.Status.PENDING);
            ticket.setProvider(null);
            Ticket saved = ticketRepository.save(ticket);
            logActivity(saved, provider, "FORWARDED", "Forwarded to manager. Reason: " + reason);
            return toDTO(saved);
        });
    }

    public List<TicketActivityDTO> getTicketActivity(Long ticketId) {
        return activityRepository.findByTicketIdOrderByCreatedAtDesc(ticketId).stream()
                .map(act -> {
                    TicketActivityDTO dto = new TicketActivityDTO();
                    dto.setId(act.getId());
                    dto.setUserName(act.getUser() != null ? act.getUser().getName() : "System");
                    dto.setUserRole(act.getUser() != null ? act.getUser().getRole().name() : "SYSTEM");
                    dto.setAction(act.getAction());
                    dto.setDetails(act.getDetails());
                    dto.setCreatedAt(act.getCreatedAt());
                    return dto;
                }).collect(Collectors.toList());
    }

    private void logActivity(Ticket ticket, User user, String action, String details) {
        activityRepository.save(new TicketActivity(ticket, user, action, details));
    }
}
