package com.gira.backend.util;

import java.util.regex.Pattern;

/**
 * Centralized validation for company IDs generated by the manager flow.
 */
public final class CompanyIdValidator {

    // Accept either the old generated form (GIRA-AB12-1234) or any
    // uppercase alphanumeric/hyphen string between 3 and 40 chars.
    private static final Pattern COMPANY_ID_PATTERN =
            Pattern.compile("^(GIRA-[A-Z0-9]{4}-\\d{4}|[A-Z0-9-]{3,40})$");

    private CompanyIdValidator() {
        // utility class
    }

    public static boolean isValid(String companyId) {
        if (companyId == null) return false;
        return COMPANY_ID_PATTERN.matcher(companyId.trim()).matches();
    }
}
